name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  inegration:
    runs-on: ubuntu-latest
    steps:
    
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - uses: actions/checkout@v2
     
      - name: Build and push Docker image
        id:   docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/cycode:latest
  
  deploy:
    if: github.ref == 'refs/heads/master'
    needs: inegration
    runs-on: ubuntu-latest
    steps:         
      - name: Copy main.tf file to remote host
        uses: appleboy/scp-action@master
        with:
          host: ec2-3-139-88-61.us-east-2.compute.amazonaws.com
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          port: 22
          rm: true
          source: "~/main.tf"
          target: "~"

      - name: Deploy k8s app on remote host using terraform
        uses: appleboy/ssh-action@master
        with:
          host: ec2-3-139-88-61.us-east-2.compute.amazonaws.com
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          port: 22
          script: |
            terraform init
            terraform apply --auto-approve
          
